/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettlementsRouteImport } from './routes/settlements'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MyServicesRouteImport } from './routes/my-services'
import { Route as MyQrCodeRouteImport } from './routes/my-qr-code'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as DeveloperSettingsRouteImport } from './routes/developer-settings'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as BankDowntimesRouteImport } from './routes/bank-downtimes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptPaymentsRouteImport } from './routes/accept-payments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettlementsIdRouteImport } from './routes/settlements.$id'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsDashboardRouteImport } from './routes/settings.dashboard'
import { Route as ApiSmsRouteImport } from './routes/api/sms'
import { Route as SettingsDashboardNotificationsRouteImport } from './routes/settings.dashboard.notifications'

const SettlementsRoute = SettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyServicesRoute = MyServicesRouteImport.update({
  id: '/my-services',
  path: '/my-services',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrCodeRoute = MyQrCodeRouteImport.update({
  id: '/my-qr-code',
  path: '/my-qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSettingsRoute = DeveloperSettingsRouteImport.update({
  id: '/developer-settings',
  path: '/developer-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const BankDowntimesRoute = BankDowntimesRouteImport.update({
  id: '/bank-downtimes',
  path: '/bank-downtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptPaymentsRoute = AcceptPaymentsRouteImport.update({
  id: '/accept-payments',
  path: '/accept-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementsIdRoute = SettlementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SettlementsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDashboardRoute = SettingsDashboardRouteImport.update({
  id: '/settings/dashboard',
  path: '/settings/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsRoute = ApiSmsRouteImport.update({
  id: '/api/sms',
  path: '/api/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDashboardNotificationsRoute =
  SettingsDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SettingsDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-payments': typeof AcceptPaymentsRoute
  '/admin': typeof AdminRoute
  '/bank-downtimes': typeof BankDowntimesRoute
  '/developer': typeof DeveloperRoute
  '/developer-settings': typeof DeveloperSettingsRoute
  '/disputes': typeof DisputesRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/my-qr-code': typeof MyQrCodeRoute
  '/my-services': typeof MyServicesRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/settlements': typeof SettlementsRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/settings/dashboard': typeof SettingsDashboardRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settlements/$id': typeof SettlementsIdRoute
  '/settings/dashboard/notifications': typeof SettingsDashboardNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-payments': typeof AcceptPaymentsRoute
  '/admin': typeof AdminRoute
  '/bank-downtimes': typeof BankDowntimesRoute
  '/developer': typeof DeveloperRoute
  '/developer-settings': typeof DeveloperSettingsRoute
  '/disputes': typeof DisputesRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/my-qr-code': typeof MyQrCodeRoute
  '/my-services': typeof MyServicesRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/settlements': typeof SettlementsRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/settings/dashboard': typeof SettingsDashboardRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settlements/$id': typeof SettlementsIdRoute
  '/settings/dashboard/notifications': typeof SettingsDashboardNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-payments': typeof AcceptPaymentsRoute
  '/admin': typeof AdminRoute
  '/bank-downtimes': typeof BankDowntimesRoute
  '/developer': typeof DeveloperRoute
  '/developer-settings': typeof DeveloperSettingsRoute
  '/disputes': typeof DisputesRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/my-qr-code': typeof MyQrCodeRoute
  '/my-services': typeof MyServicesRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/settlements': typeof SettlementsRouteWithChildren
  '/api/sms': typeof ApiSmsRoute
  '/settings/dashboard': typeof SettingsDashboardRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settlements/$id': typeof SettlementsIdRoute
  '/settings/dashboard/notifications': typeof SettingsDashboardNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-payments'
    | '/admin'
    | '/bank-downtimes'
    | '/developer'
    | '/developer-settings'
    | '/disputes'
    | '/help'
    | '/invoices'
    | '/login'
    | '/my-qr-code'
    | '/my-services'
    | '/payments'
    | '/pricing'
    | '/products'
    | '/refunds'
    | '/reports'
    | '/settlements'
    | '/api/sms'
    | '/settings/dashboard'
    | '/settings/profile'
    | '/settings/users'
    | '/settlements/$id'
    | '/settings/dashboard/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-payments'
    | '/admin'
    | '/bank-downtimes'
    | '/developer'
    | '/developer-settings'
    | '/disputes'
    | '/help'
    | '/invoices'
    | '/login'
    | '/my-qr-code'
    | '/my-services'
    | '/payments'
    | '/pricing'
    | '/products'
    | '/refunds'
    | '/reports'
    | '/settlements'
    | '/api/sms'
    | '/settings/dashboard'
    | '/settings/profile'
    | '/settings/users'
    | '/settlements/$id'
    | '/settings/dashboard/notifications'
  id:
    | '__root__'
    | '/'
    | '/accept-payments'
    | '/admin'
    | '/bank-downtimes'
    | '/developer'
    | '/developer-settings'
    | '/disputes'
    | '/help'
    | '/invoices'
    | '/login'
    | '/my-qr-code'
    | '/my-services'
    | '/payments'
    | '/pricing'
    | '/products'
    | '/refunds'
    | '/reports'
    | '/settlements'
    | '/api/sms'
    | '/settings/dashboard'
    | '/settings/profile'
    | '/settings/users'
    | '/settlements/$id'
    | '/settings/dashboard/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptPaymentsRoute: typeof AcceptPaymentsRoute
  AdminRoute: typeof AdminRoute
  BankDowntimesRoute: typeof BankDowntimesRoute
  DeveloperRoute: typeof DeveloperRoute
  DeveloperSettingsRoute: typeof DeveloperSettingsRoute
  DisputesRoute: typeof DisputesRoute
  HelpRoute: typeof HelpRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MyQrCodeRoute: typeof MyQrCodeRoute
  MyServicesRoute: typeof MyServicesRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  RefundsRoute: typeof RefundsRoute
  ReportsRoute: typeof ReportsRoute
  SettlementsRoute: typeof SettlementsRouteWithChildren
  ApiSmsRoute: typeof ApiSmsRoute
  SettingsDashboardRoute: typeof SettingsDashboardRouteWithChildren
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settlements': {
      id: '/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-services': {
      id: '/my-services'
      path: '/my-services'
      fullPath: '/my-services'
      preLoaderRoute: typeof MyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr-code': {
      id: '/my-qr-code'
      path: '/my-qr-code'
      fullPath: '/my-qr-code'
      preLoaderRoute: typeof MyQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-settings': {
      id: '/developer-settings'
      path: '/developer-settings'
      fullPath: '/developer-settings'
      preLoaderRoute: typeof DeveloperSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-downtimes': {
      id: '/bank-downtimes'
      path: '/bank-downtimes'
      fullPath: '/bank-downtimes'
      preLoaderRoute: typeof BankDowntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-payments': {
      id: '/accept-payments'
      path: '/accept-payments'
      fullPath: '/accept-payments'
      preLoaderRoute: typeof AcceptPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlements/$id': {
      id: '/settlements/$id'
      path: '/$id'
      fullPath: '/settlements/$id'
      preLoaderRoute: typeof SettlementsIdRouteImport
      parentRoute: typeof SettlementsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dashboard': {
      id: '/settings/dashboard'
      path: '/settings/dashboard'
      fullPath: '/settings/dashboard'
      preLoaderRoute: typeof SettingsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms': {
      id: '/api/sms'
      path: '/api/sms'
      fullPath: '/api/sms'
      preLoaderRoute: typeof ApiSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dashboard/notifications': {
      id: '/settings/dashboard/notifications'
      path: '/notifications'
      fullPath: '/settings/dashboard/notifications'
      preLoaderRoute: typeof SettingsDashboardNotificationsRouteImport
      parentRoute: typeof SettingsDashboardRoute
    }
  }
}

interface SettlementsRouteChildren {
  SettlementsIdRoute: typeof SettlementsIdRoute
}

const SettlementsRouteChildren: SettlementsRouteChildren = {
  SettlementsIdRoute: SettlementsIdRoute,
}

const SettlementsRouteWithChildren = SettlementsRoute._addFileChildren(
  SettlementsRouteChildren,
)

interface SettingsDashboardRouteChildren {
  SettingsDashboardNotificationsRoute: typeof SettingsDashboardNotificationsRoute
}

const SettingsDashboardRouteChildren: SettingsDashboardRouteChildren = {
  SettingsDashboardNotificationsRoute: SettingsDashboardNotificationsRoute,
}

const SettingsDashboardRouteWithChildren =
  SettingsDashboardRoute._addFileChildren(SettingsDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptPaymentsRoute: AcceptPaymentsRoute,
  AdminRoute: AdminRoute,
  BankDowntimesRoute: BankDowntimesRoute,
  DeveloperRoute: DeveloperRoute,
  DeveloperSettingsRoute: DeveloperSettingsRoute,
  DisputesRoute: DisputesRoute,
  HelpRoute: HelpRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MyQrCodeRoute: MyQrCodeRoute,
  MyServicesRoute: MyServicesRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  RefundsRoute: RefundsRoute,
  ReportsRoute: ReportsRoute,
  SettlementsRoute: SettlementsRouteWithChildren,
  ApiSmsRoute: ApiSmsRoute,
  SettingsDashboardRoute: SettingsDashboardRouteWithChildren,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
